app:
  name: anuglar2-spring-jwt

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

server:
  port: 8080


spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost/concretepage
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver


#spring:
#  jpa:
#    hibernate:
#      # possible values: validate | update | create | create-drop
#      ddl-auto: update
#  datasource:
#    schema: db691188544
#    url: jdbc:mysql://db691188544.db.1and1.com
#    username: dbo691188544
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
